apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: energy-consumption
resources:
  - ../../base
components:
  - ../../components/ingress
  - ../../components/db
patches:
  - path: resources-patch.yaml
images:
  - name: jknetl/energy-consumption
    newTag: 38fcd87
