spring:
  application:
    name: energy-consumption
  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY}
    public-key: ${APP_JWT_PUBLIC_KEY}

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
