spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_consumption
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

app:
  init:
    user-a-password: ${USER_A_PASSWORD}
    user-b-password: ${USER_B_PASSWORD}