apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption
spec:
  replicas: 2
  selector:
    matchLabels:
      app: energy-consumption
  template:
    metadata:
      labels:
        app: energy-consumption
    spec:
      containers:
        - name: energy-consumption
          image: jknetl/energy-consumption:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: energy-consumption-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: energy-consumption-db-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: energy-consumption-db-app
                  key: password
            - name: APP_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: energy-consumption-jwt
                  key: private-key
            - name: APP_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: energy-consumption-jwt
                  key: public-key
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 300m
              memory: 512Mi
              ephemeral-storage: 256Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 5
            failureThreshold: 3
